---
collections:
  - name: community.docker
    version: 3.13.1
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.general
    version: 9.5.0
    type: galaxy
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.16.1
    type: galaxy
    source: https://galaxy.ansible.com
