---
collections:
  - name: community.docker
    version: 3.12.1
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.general
    version: 9.4.0
    type: galaxy
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.15.4
    type: galaxy
    source: https://galaxy.ansible.com
