---
collections:
  - name: community.docker
    version: 4.0.1
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.general
    version: 10.0.0
    type: galaxy
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.16.2
    type: galaxy
    source: https://galaxy.ansible.com
