---
collections:
  - name: community.docker
    version: 4.5.1
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.general
    version: 10.4.0
    type: galaxy
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.16.3
    type: galaxy
    source: https://galaxy.ansible.com
