---
collections:
  - name: community.docker
    version: 4.8.2
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.general
    version: 11.4.1
    type: galaxy
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.18.0
    type: galaxy
    source: https://galaxy.ansible.com
