---
collections:
  - name: community.docker
    version: 4.6.1
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.general
    version: 11.0.0
    type: galaxy
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.16.4
    type: galaxy
    source: https://galaxy.ansible.com
