---
collections:
  - name: community.docker
    version: 3.4.8
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.general
    version: 7.3.0
    type: galaxy
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.10.3
    type: galaxy
    source: https://galaxy.ansible.com
