---
collections:
  - name: community.docker
    version: 5.0.5
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.general
    version: 12.3.0
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.proxmox
    version: 1.5.0
    type: galaxy
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.18.1
    type: galaxy
    source: https://galaxy.ansible.com
