---
collections:
  - name: community.docker
    version: 3.4.7
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.general
    version: 7.0.1
    type: galaxy
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.10.2
    type: galaxy
    source: https://galaxy.ansible.com
