---
collections:
  - name: community.docker
    version: 3.4.6
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.general
    version: 7.0.0
    type: galaxy
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.10.1
    type: galaxy
    source: https://galaxy.ansible.com
