---
collections:
  - name: community.docker
    version: 5.2.0
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.general
    version: 12.6.0
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.proxmox
    version: 1.6.0
    type: galaxy
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.20.1
    type: galaxy
    source: https://galaxy.ansible.com
