---
collections:
  - name: community.docker
    version: 3.4.11
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.general
    version: 7.5.1
    type: galaxy
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.10.3
    type: galaxy
    source: https://galaxy.ansible.com
