---
collections:
  - name: community.docker
    version: 3.9.0
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.general
    version: 8.5.0
    type: galaxy
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.12.1
    type: galaxy
    source: https://galaxy.ansible.com
