---
collections:
  - name: community.docker
    version: 3.10.1
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.general
    version: 8.6.1
    type: galaxy
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.13.0
    type: galaxy
    source: https://galaxy.ansible.com
