---
collections:
  - name: community.docker
    version: 3.10.4
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.general
    version: 9.1.0
    type: galaxy
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.15.3
    type: galaxy
    source: https://galaxy.ansible.com
