---
collections:
  - name: community.docker
    version: 3.4.11
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.general
    version: 8.1.0
    type: galaxy
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.11.0
    type: galaxy
    source: https://galaxy.ansible.com
