---
collections:
  - name: community.docker
    version: 3.10.3
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.general
    version: 9.0.1
    type: galaxy
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.15.2
    type: galaxy
    source: https://galaxy.ansible.com
