---
collections:
  - name: community.docker
    version: 3.8.1
    type: galaxy
    source: https://galaxy.ansible.com

  - name: community.general
    version: 8.4.0
    type: galaxy
    source: https://galaxy.ansible.com

  - name: containers.podman
    version: 1.12.0
    type: galaxy
    source: https://galaxy.ansible.com
