name: Test image
on:
  merge_group:
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Build image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: Dockerfile
